version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Ibkg2jaW/CZVGOPCguH2cmnGYyZg60XzqoLM9NahKYIRVf5Kt5sgm7SeF6gdnrto
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: nKINbFDUnrA1rYVUPmk+W6Ddg8Dp3Eq5FzoRSPuEQP7dU4HBg19SBxFjTX91hhm2
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
